#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     15

yabai -m config auto_balance off
yabai -m config split_ratio 0.5

yabai -m config focus_follows_mouse off

yabai -m config window_border on
yabai -m config window_border_placement inset
yabai -m config window_border_width 3
yabai -m config window_border_radius 0
yabai -m config active_window_border_color 0xff0f6288
yabai -m config normal_window_border_color 0x00000000
yabai -m config insert_window_border_color 0xffd75f5f

yabai -m rule --add app=Finder title=Copy manage=off
yabai -m rule --add app='Fantastical 2' manage=off
yabai -m rule --add app='Cisco AnyConnect Secure Mobility Client' manage=off
yabai -m rule --add app='Cisco Webex Meetings' manage=off
yabai -m rule --add app=ColorSlurp manage=off
yabai -m rule --add app='System Preferences' manage=off

echo 'yabai configuration loaded..'
