#!/usr/bin/env python

import sys
import json
from plistlib import readPlist
from StringIO import StringIO

if __name__ == '__main__':
    filename = sys.argv[1]
    with open(filename, 'r') as f:
        data = readPlist(StringIO(f.read()))
    with open(filename + '.json', 'w') as json_file:
        json_file.write(json.dumps(data))
