
PATH=$HOME/.bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# virtualenvwrapper environments home
WORKON_HOME=$HOME/.virtualenvs/

# Disable the regular virtualenv prompt, "(venv_name)$"
VIRTUAL_ENV_DISABLE_PROMPT=true

# Pip related settings
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true

# RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

if [ "`uname`" = 'Darwin' ]
then
	# Update Ruby Gems path for Homebrew
	# GEM_HOME="$(brew --prefix)"
fi

# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

