PATH=$HOME/.bin:$PATH

# rbenv
if which rbenv &>/dev/null; then eval "$(rbenv init -)"; fi

# nvm
# if [[ -s $HOME/.nvm/nvm.sh ]]; then source $HOME/.nvm/nvm.sh; fi

# Postgres.app
if [[ -d /Applications/Postgres.app/Contents/MacOS/bin ]]
then export PATH=/Applications/Postgres.app/Contents/MacOS/bin:$PATH
fi

# virtualenvwrapper
WORKON_HOME=$HOME/.virtualenvs/
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true
VIRTUAL_ENV_DISABLE_PROMPT=true # Disable "(venv_name}$" prompt
if which virtualenvwrapper.sh &>/dev/null; then source virtualenvwrapper.sh; fi
