# Automatically start tmux if it isn't attached
# [[ $TERM != "screen" ]] && [[ $TERM != "screen-256color" ]] && tmux && exit

ZSH=$HOME/.oh-my-zsh
ZSH_THEME=coarse-kibble

plugins=(django git github mercurial node pip powder rake rbenv vundle)
if [[ `uname` == 'Darwin' ]]; then plugins+=brew; else plugins+=debian; fi

source $ZSH/oh-my-zsh.sh

export EDITOR=subl

# ls colors
if [ "`uname`" = 'Darwin' ]
# Solarized
# then export LSCOLORS=exfxcxdxbxegedabagexex
# Kibble
then export LSCOLORS=exBxcxfxbxegedabagacad
else export LS_COLORS='di=34;40:ln=1;;40:so=32;40:pi=35;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:'
fi

# =========
# Functions
# =========

# Get the SLOC count of given files. Ignores blank, #-, and //-commented lines.
sloc() {
  sed -e '/^\s*[#\(\/\/\)].*/d' -e '/^\s*$/d' $@ | wc -l
}

mkcd() {
  mkdir $1
  cd $1
}

source $HOME/.files/zsh/colors.sh

# =======
# Aliases
# =======

# Which vim should I use?
if [[ "`uname`" != 'Darwin' ]]
then alias vim="vim"
else alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
fi

alias addrepo="sudo add-apt-repository" # add-apt-repository is just too verbose
alias serve="python -m SimpleHTTPServer 8060" # Serve current directory, thanks Python
alias be="bundle exec"

# Somehow, and I don't know how, this keeps tmux from screwing up terminal vim's
# colours
alias tmux="TERM=screen-256color-bce tmux"

# Zsh does odd things sometimes, stop correcting me!
for cmd in "cp mv mkdir tmux rbenv ncmpcpp subl powder bundle vundle pip"; do
  alias $cmd="nocorrect $cmd"
done

alias weather="weatherman"
alias hastier="cat $1 | haste | pbcopy"

echo "Did you update your system today?"
